services:
    behat.spawner.suite_listener:
        class: Behat\SpawnerExtension\Listener\SuiteListener
        arguments:
            - %behat.spawner.commands%
            - %behat.spawner.working_directory%
            - '%behat.spawner.nix_prefix%'
            - '%behat.spawner.win_prefix%'
            - '%behat.spawner.sleep%'
        tags:
            - { name: behat.event_subscriber }
