services:
    behat.spawner.suite_listener:
        class: Restoclub\Behat\ServersExtension\Listener\SpawnerListener
        arguments:
            - %behat.spawner.commands%
            - %behat.spawner.working_directory%
            - '%behat.spawner.nix_prefix%'
            - '%behat.spawner.win_prefix%'
        tags:
            - { name: behat.event_subscriber }
